-- Generated by `lake exe gen`; do not edit (`UNTRUSTED_XLATE`).
import Ledger.Core

namespace Corpus

/-- Registry row generated from `corpus/ledger.kb/least-fix.md`. -/
def C.LEAST_FIX : ClaimMeta where
  label := `LEAST_FIX
  hash := 0x8b7ca7997a6b873c
  text := "Provenness is the least fixpoint of ASSERT — cycles are unproven."
  premises := [`ASSERT]
  evidence := [{ source := .user, judged := 0x8b7ca7997a6b873c, date := "2026-07-28" }]

/-- The registry (`NATIVE!`), one row per corpus claim, in
sorted-path order. -/
def ledger : Ledger := [
  { row := C.LEAST_FIX, depth := .stated }]

end Corpus
